import{a as w,S as L,i as n}from"./assets/vendor-C4-ZuMk8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const S="46874695-aa87c3456f3cd5bd5c148909d",v="https://pixabay.com/api/";let d=1;async function g(o){const t={key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:d,per_page:15},a=await w.get(v,{params:t});return d+=1,a.data.hits}function P(){d=1}function y(o){const t=document.querySelector(".gallery"),a=o.map(({webformatURL:e,largeImageURL:r,tags:s,likes:p,views:h,comments:b,downloads:_})=>`
    <div class="gallery__item">
      <a class="gallery__link" href="${r}">
        <img class="gallery__image" src="${e}" alt="${s}" />
        <div class="gallery__info">
          <p class="gallery__info-item"><b>Likes:</b> ${p}</p>
          <p class="gallery__info-item"><b>Views:</b> ${h}</p>
          <p class="gallery__info-item"><b>Comments:</b> ${b}</p>
          <p class="gallery__info-item"><b>Downloads:</b> ${_}</p>
        </div>
      </a>
    </div>
  `).join("");t.insertAdjacentHTML("beforeend",a),new L(".gallery a").refresh()}function q(){document.querySelector(".gallery").innerHTML=""}const E=document.querySelector("#search-form"),l=document.querySelector("#load-more"),u=document.querySelector("#loader");let i="";function f(){u.style.display="block"}function m(){u.style.display="none"}E.addEventListener("submit",async o=>{if(o.preventDefault(),i=o.target.searchQuery.value.trim(),console.log("Форма подана"),!i){n.warning({title:"Warning",message:"Please enter a search query!"});return}f(),q(),P(),l.style.display="none";try{const t=await g(i);console.log("Запит API пройшов успішно",t),t.length===0?n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(y(t),l.style.display="block")}catch{n.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{m()}});l.addEventListener("click",async()=>{f();try{const o=await g(i);console.log("Завантаження додаткових зображень",o),y(o),o.length<15&&(l.style.display="none",n.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}));const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{n.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{m()}});
//# sourceMappingURL=index.js.map
