import{a as _,S as g,i as s}from"./assets/vendor-C4-ZuMk8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const L="46874695-aa87c3456f3cd5bd5c148909d",S="https://pixabay.com/api/";let d=1;async function y(o){const t={key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:d,per_page:15},n=await _.get(S,{params:t});return d+=1,n.data.hits}function v(){d=1}function u(o){const t=document.querySelector(".gallery"),n=o.map(({webformatURL:i,largeImageURL:e,tags:r,likes:a,views:h,comments:w,downloads:b})=>`
    <div class="gallery__item">
      <a class="gallery__link" href="${e}">
        <img class="gallery__image" src="${i}" alt="${r}" />
        <div class="gallery__info">
          <p class="gallery__info-item"><b>Likes:</b> ${a}</p>
          <p class="gallery__info-item"><b>Views:</b> ${h}</p>
          <p class="gallery__info-item"><b>Comments:</b> ${w}</p>
          <p class="gallery__info-item"><b>Downloads:</b> ${b}</p>
        </div>
      </a>
    </div>
  `).join("");t.insertAdjacentHTML("beforeend",n),window.lightbox&&window.lightbox.destroy(),window.lightbox=new g(".gallery a")}function P(){document.querySelector(".gallery").innerHTML=""}const q=document.querySelector("#search-form"),c=document.querySelector("#load-more"),f=document.querySelector("#loader");let l="";document.addEventListener("DOMContentLoaded",()=>{window.lightbox=new g(".gallery a")});function m(){f.style.display="block"}function p(){f.style.display="none"}q.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.searchQuery.value.trim(),console.log("Форма подана"),!l){s.warning({title:"Warning",message:"Please enter a search query!"});return}m(),P(),v(),c.style.display="none";try{const t=await y(l);console.log("Запит API пройшов успішно",t),t.length===0?s.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(u(t),window.lightbox.refresh(),c.style.display="block")}catch{s.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{p()}});c.addEventListener("click",async()=>{m();try{const o=await y(l);console.log("Завантаження додаткових зображень",o),u(o),o.length<15&&(c.style.display="none",s.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}));const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{s.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{p()}});
//# sourceMappingURL=index.js.map
